name: build-windows-package

on:
  push:
    branches: [ master ]

env:
  DESKTOP_OSS_BUCKET: ${{ secrets.DESKTOP_OSS_BUCKET }}
  DESKTOP_OSS_REGION: ${{ secrets.DESKTOP_OSS_REGION }}
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}

jobs:
  build:
    env:
      PUBLISH_FILE_EXT: exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download GTK to install fabricjs (node-canvas)
        # https://github.com/Automattic/node-canvas/wiki/Installation:-Windows
        run: |
          curl -kL http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip -o gtk.zip
          7z x gtk.zip -o"c:\\GTK"
        shell: bash

      - name: Npm install
        run: npm ci

      - name: Build and publish windows package
        run: npm run package:windows
        shell: bash
