name: build-mac-package

on:
  push:
    branches: [ master ]

env:
  DESKTOP_OSS_BUCKET: ${{ secrets.DESKTOP_OSS_BUCKET }}
  DESKTOP_OSS_REGION: ${{ secrets.DESKTOP_OSS_REGION }}
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_KEY_SECRET: ${{ secrets.ALICLOUD_KEY_SECRET }}

jobs:
  build:
    env:
      PUBLISH_FILE_EXT: dmg
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Npm install
        run: npm ci

      - name: Build and publish mac package
        run: npm run package:mac
        shell: bash
