name: build-windows-package

on:
  push:
    branches:
      - develop
      - master
    tags:
      - '*'

env:
  OSS_BUCKET: ${{ github.ref == 'refs/heads/master' && 'cbt-cloudswitcher-prod' || 'cbt-cloudswitcher-test' }}
  OSS_REGION: ${{ secrets.OSS_REGION }}
  OSS_ACCESS_KEY: ${{ secrets.OSS_ACCESS_KEY }}
  OSS_SECRET_KEY: ${{ secrets.OSS_SECRET_KEY }}
  VERSION: ${{ github.sha }}

jobs:
  build:
    env:
      PUBLISH_FILE_EXT: exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download GTK to install fabricjs (node-canvas)
        # https://github.com/Automattic/node-canvas/wiki/Installation:-Windows
        run: |
          curl -kL http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip -o gtk.zip
          7z x gtk.zip -o"c:\\GTK"
        shell: bash

      - name: Npm install
        run: npm ci
        shell: bash

      - name: Update VERSION for releases
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: Build and publish windows package
        run: npm run package:windows:${{ github.ref == 'refs/heads/master' && 'prod' || 'test' }}
        shell: bash

      - name: Download ossutil and copy package to the latest folder
        run: |
          curl -kL "https://gosspublic.alicdn.com/ossutil/1.7.3/ossutil64.zip?spm=a2c63.p38356.a3.5.7ae22454Qs1qHC&file=ossutil64.zip" -o ossutil64.zip
          7z x ossutil64.zip -o"ossutil"
          ossutil/ossutil64/ossutil64.exe config -e ${{ env.OSS_REGION }}.aliyuncs.com -i ${{ env.OSS_ACCESS_KEY }} -k ${{ env.OSS_SECRET_KEY }}
          ossutil/ossutil64/ossutil64.exe cp -f \
            oss://${{ env.OSS_BUCKET }}/desktop/${{ env.VERSION }}/win/cloudswitcher-desktop.exe \
            oss://${{ env.OSS_BUCKET }}/desktop/latest/win/cloudswitcher-desktop.exe
        shell: bash
