name: build-windows-package

on:
  push:
    branches: [ master ]

env:
  DESKTOP_OSS_BUCKET: ${{ secrets.DESKTOP_OSS_BUCKET }}
  DESKTOP_OSS_REGION: ${{ secrets.DESKTOP_OSS_REGION }}
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_KEY_SECRET: ${{ secrets.ALICLOUD_KEY_SECRET }}

jobs:
  build:
    env:
      PUBLISH_FILE_EXT: exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Npm install
        run: npm ci

      - name: Build and publish windows package
        run: npm run package:windows
        shell: bash
